#define IDI_ICON1 101
#define IDR_MAINMENU 102

// Menu IDs
#define IDM_SETTINGS 201
#define IDM_EXIT 202

// Dialog IDs
#define IDD_SETTINGS_DIALOG 301

// Control IDs
#define IDC_DIRECTORY_EDIT 101
#define IDC_BROWSE_BUTTON 102
#define IDC_EXTENSION_COMBO 103
#define IDC_CUSTOM_EXT_EDIT 104
#define IDC_BUILD_INDEX_BUTTON 105
#define IDC_OPEN_RANDOM_BUTTON 106
#define IDC_RECENT_FILES_LIST 107
#define IDC_FOLDER_INFO_STATIC 110

#define IDC_STATIC -1
